---
name: inforamclub
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  get: 4.1.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.0.0
  flutter_duration_picker:
    path: ./lib/app/modules/service_form/views/widgets/flutter_duration_picker-master
  cool_alert: ^1.1.0
  progress_state_button:
    path: ./lib/app/modules/service_details/widgets/progress-state-button-master/progress-state-button-master
  flutter_slider_drawer: ^2.0.0
  drawerbehavior: ^2.1.0
  firebase_messaging: ^9.1.3
  dio: ^4.0.0
  google_maps_flutter: ^2.0.3
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.5
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.2
  cloud_firestore: ^1.0.7
  cached_network_image: ^3.0.0
  google_sign_in: ^5.0.2
  geolocator: ^7.0.3
  modal_progress_hud: ^0.1.3
  url_launcher: ^5.7.6
  flutter_svg: ^0.21.0+1
  path_provider: ^2.0.1
  flutter_platform_widgets: ^1.2.0
  formz: ^0.3.2
  enum_to_string: ^2.0.1

  reactive_forms: ^10.2.0
  rounded_loading_button:
    path: ./lib/app/modules/login/views/widgets/flutter_rounded_loading_button-master
  image_picker: ^0.7.4
  intl: ^0.17.0
  flutter_swiper: ^1.1.6
  flutter_page_indicator: null
  sleek_circular_slider: ^2.0.0
  flutter_glow: ^0.2.0
  font_awesome_flutter: ^9.0.0
  flutter_datetime_picker: ^1.5.0
#  get_storage: ^2.0.2
  flutter_local_notifications: ^5.0.0+4
  toggle_switch: ^0.1.9
  rxdart: ^0.26.0
  date_time_picker: ^2.0.0
  flutter_form_builder: ^6.0.0
  firebase_storage: ^8.0.4
  uuid: ^3.0.4
  circular_countdown_timer: ^0.2.0
  flutter_countdown_timer: ^4.1.0
  dartz: ^0.9.2
  shimmer: ^2.0.0
  auto_size_text: ^2.1.0
  responsive_framework: ^0.1.0
  file_picker: ^3.0.1
  flutter_image_compress: ^1.0.0
  heic_to_jpg: ^0.2.0
  hive: ^2.0.4
  table_calendar:

  form_builder_file_picker:
    path: ./lib/app/modules/service_type_form/views/widgets/form_builder_file_picker-master

dependency_overrides:
  firebase_core_platform_interface: ^4.0.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.8+4
  flutter_launcher_icons: ^0.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/translations/

flutter_native_splash:
  color: "#FFE300"
  image: assets/images/logo.png
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"


